create table consumer(
id	Varchar(32) COMMENT	'32 UUID',
first_name	Varchar(16) COMMENT	'名',
last_name	Varchar(16) COMMENT	'姓',
email_address	Varchar(64) COMMENT	'邮箱',
mobile_phone	Varchar(11) COMMENT	'手机',
mobile_area_code	Varchar(5) COMMENT	'区号',	
birthday_day	Varchar(10) COMMENT	'2018-06-27',
birthday_month		Varchar(2) COMMENT	'月',
birthday_year		Varchar(4) COMMENT	'年',
title_salutation	Varchar(64) COMMENT	'称谓',
gender	Varchar(16) COMMENT	'性别',
vip_number	Varchar(64)	COMMENT 'Vip编号',
loyalty_points	varchar(5) COMMENT	'积分',
loyalty_tier	Varchar(16) COMMENT	'等级',
loyalty_points_expiry_date	Varchar(24) COMMENT	'2018-06-29',
next_loyalty_tier	Varchar(16) COMMENT	'下一个等级',
points_to_next_tier	Varchar(16) COMMENT	'下一等级需要的积分',
previous_loyalty_tier	Varchar(16) COMMENT	'前一个等级',
last_birthday_discount_redemption_date varchar(32)	COMMENT	'最后生日礼券兑换时间',
openid	Varchar(28) COMMENT '微信openid',
unionid	Varchar(28) COMMENT '微信unionid',
status	Varchar(16) COMMENT	'绑定状态：pending,finished',
crmid	Varchar(64)	COMMENT 'scv scrmid',
channel	Varchar(16) COMMENT	'weibo/wechat/wechat ad/baidu/brandsite/other',
source	varchar(8) COMMENT	'WE,WPOS,WSITE(ESTORE,CLUB)',
created_time		timestamp DEFAULT now(),
last_updated_time		timestamp DEFAULT now());
