mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations:
  - classpath:mapper/*.xml
  - classpath:tkmapper/*.xml
  type-aliases-package: cn.d1m.pandora.entry
spring:
  jackson:
    serialization:                        #null字段自动忽略
      indent_output: true                 #格式化打印json字符串
      fail_on_empty_beans: false          #循环依赖自动拆开
    default-property-inclusion: non_null  #null输出忽略
   # date-format: "yyyy-MM-dd HH:mm:ss"    #默认日期格式化
    deserialization:
      fail_on_unknown_properties: false

logging:
  config: ${log.path:logs}/log4j2.xml


#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

feign:
  client:
    default-config: main
    config:
      main:
        readTimeout: 5000
        loggerLevel: HEADERS
ribbon:
  ReadTimeout: 5000

